app:
  modes:
    - single
    - parser-list
    - build-site-list
    - edit-single-page
  defaultMode: single
  singlePageUrl: "https://oper.ru/video/"
  listPageUrls:
    - "https://oper.ru/video/"
  outputDir: "out-files"
  maxItems: 0
  userAgent: "TextHarvesterBot/0.1 (+https://github.com/alexmnv01/TextHarvester)"
  timeoutSeconds: 15
  dryRun: false
